### ISSUE TITLE
Caprover Guacamole Extentions

### ISSUE THREAD

**Issue by prononext** [christopher-kapic/caprover-guacamole#2]
**Is there any way to integrate extentions on that Caprover Guacamole installation?**

https://guacamole.apache.org/releases/1.4.0/

Especially the TOTP 2-Factor Authentification
https://apache.org/dyn/closer.lua/guacamole/1.4.0/binary/guacamole-auth-totp-1.4.0.tar.gz

**Comment by christopher-kapic** [comment]
I'm not sure, and to be honest it will take me a while to get to it. Check back in a month and I might have more time. (Not trying to be rude, I just have a lot going on right now).

**Comment by prononext** [comment]
Thank you, the Caprover Guacamole with your help is already quite perfect. Very nice work! 

Maybe you find inspiration from this repo https://hub.docker.com/r/oznu/guacamole/
Its a little outdated but has extention functionality...

**Comment by christopher-kapic** [comment]
Hey @prononext, I'm not going to pursue this issue. If you find a solution, feel free to submit a PR with instructions. For now, I'm going to close this issue.
